// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.API.Database;

namespace TMS.API.Migrations
{
    [DbContext(typeof(TMSContext))]
    [Migration("20211114093450_relation_changes_userapproval")]
    partial class relation_changes_userapproval
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TMS.Models.Model.BreakTime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("rTimeSheet")
                        .HasColumnType("int");

                    b.Property<int>("rUser")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BreakTimes");
                });

            modelBuilder.Entity("TMS.Models.Model.LeaveTime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("rTimeSheet")
                        .HasColumnType("int");

                    b.Property<int>("rUser")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("LeaveTimes");
                });

            modelBuilder.Entity("TMS.Models.Model.TimeSheet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DayDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("flgBreak")
                        .HasColumnType("bit");

                    b.Property<bool>("flgLeave")
                        .HasColumnType("bit");

                    b.Property<int>("rUser")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("TMS.Models.Model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LeaveHours")
                        .HasColumnType("float");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SBOId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("flgAprover")
                        .HasColumnType("bit");

                    b.Property<bool>("flgBreak")
                        .HasColumnType("bit");

                    b.Property<bool>("flgSuper")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "admin@admin.com",
                            LeaveHours = 80.0,
                            Password = "123",
                            SBOId = "",
                            UserCode = "admin",
                            UserName = "admin",
                            flgAprover = false,
                            flgBreak = false,
                            flgSuper = false
                        });
                });

            modelBuilder.Entity("TMS.Models.Model.UserApproval", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rDocument")
                        .HasColumnType("int");

                    b.Property<int>("rUser")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserApprovals");
                });
#pragma warning restore 612, 618
        }
    }
}
